@startuml

class BaseObject {
  +config
  +fields
  +className
  +id
  +__construct()
  +fields()
  +fillObject()
  +id()
  +get()
  +set()
  +deleteObject()
  +saveObject()
  +saveRequestObject()
  +newId()
  +getObjects()
  +getConfig()
  +isJson()
  +getCryptKeys()
  +enCrypteOnly()
  +enCrypte()
  +deCrypte()
  +saveFileEnCrypted()
  +loadFileDeCrypted()
  +serializeObject()
  +removeFromArray()
  +cleanObject()
  +deleteDirectory()
  +generateRandomString()
}

class Controller {
  +resultType
  +viewName
  +viewObject
  +objectId
  +className
  +actions
  +templates
  +config
  +presentationObject
  +role
  +object
  +response
  +__construct()
  +init()
  +getPresentationObject()
  +getViewObject()
  +getResultType()
  +setObject()
  +setRole()
  +execute()
  +checkRole()
  +view()
  +json()
  +savePostData()
  +checkPermissions()
  +responseData()
  +renderView()
  +executeActions()
}

class Game {
  +name
  +title
  +description
  +player
  +hunter
  +management
  +start
  +duration
  +avatar
  +pingInterval
  +speedPingInterval
  +speedPingCount
  +startPosition
  +exitPosition
  +images
  +tmpImageAdd
  +showPlayer
  +trackInterval
  +showNames
  +playingFieldCenterPosition
  +playingFieldSize
  +addGameImage()
  +deleteGameImage()
  +avatarFileUploaded()
  +startGame()
  +addGamePlayDataToGame()
  +deleteGame()
  +saveNewGame()
  +removePlayerProperties()
  +addPlayerToGame()
  +addHunterToGame()
  +addManagementToGame()
  +setPlayerIdToTemplate()
  +archiveGame()
  +gameplay()
}

class Gameplay {
  +gameplayObject
  +gameplayPath
  +currentPlayer
  +currentPlayerGameRole
  +currentPlayerTracking
  +gameSettings
  +messages
  +gameplayRoles
  +isRunning
  +startTimestamp
  +endTimestamp
  +__construct()
  +init()
  +transferStatistics()
  +setStatisticProperty()
  +addTracking()
  +getGameSettings()
  +calcDistance()
  +calcPlayerDistances()
  +getAllPlayerPositions()
  +getPlayerPosition()
  +saveGameplay()
  +saveMessages()
  +silentHunt()
  +checkRulesAndAddSystemMessages()
  +getGameplayState()
  +getGameplaySpeedHunt()
  +captured()
  +speedHunt()
  +track()
  +message()
  +stopped()
  +statistic()
}

class Player {
  +name
  +password
  +role
  +email
  +image
  +games
  +title
  +description
  +asPlayerCountSteps
  +asHunterCountSteps
  +asManagementCountSteps
  +asPlayerDistance
  +asHunterDistance
  +asManagementDistance
  +asPlayerCountGames
  +asHunterCountGames
  +asManagementCountGames
  +asPlayerTime
  +asHunterTime
  +asManagementTime
  +asPlayerViolationOfTheRules
  +asHunterViolationOfTheRules
  +asManagementViolationOfTheRules
  +asPlayerSpeedHunts
  +asHunterSpeedHunts
  +asManagementSpeedHunts
  +asPlayerCaptured
  +asHunterCaptured
  +asManagementCaptured
  +asPlayerCountMessages
  +asHunterCountMessages
  +asManagementCountMessages
  +asPlayerCountMessagesAll
  +asHunterCountMessagesAll
  +asManagementCountMessagesAll
  +newPlayer()
  +addGamesToTemplate()
  +checkLogin()
  +getPlayerIdFromCookie()
  +login()
  +avatarFileUploaded()
  +deletePlayer()
  +deletePlayerFromApp()
  +setup()
  +getPlayerList()
  +getGameArchiveList()
  +backFromArchiveGame()
  +deleteArchiveGame()
}

class Presentation {
  +templateVars
  +config
  +__construct()
  +initTemplateVars()
  +assignTemplateVar()
  +processTemplate()
  +stringToTimestamp()
  +timestampToString()
  +writeCookie()
  +deleteCookie()
  +getCookieProperty()
  +newFormError()
  +getBaseUrl()
  +getFullUrl()
  +sendHtmlMail()
  +validateFields()
  +logToFile()
  +shortText()
  +cleanId()
  +cors()
  +getJsonHeader()
  +getJavaScriptHeader()
}

BaseObject <|-- Game
Game <|-- Gameplay
BaseObject <|-- Player
@enduml
